<a class="btn btn-success" href="<?=$this->url('product', ['action' => 'add'])?>">Добавить</a>
<br>
<div class="row">

    <div class="col-md-3">
        #
    </div>

    <div class="col-md-3">
        Название
    </div>

    <div class="col-md-3">
        Категория
    </div>
    <div class="col-md-3">

    </div>
</div>
<div class="row">
    <?php
    foreach ($this->products as $product):
        ?>
        <div class="col-md-3">
            <?=$product->id?>
        </div>

        <div class="col-md-3">
            <?=$product->name?>
        </div>

        <div class="col-md-3">
            <?=$product->category?>
        </div>

        <div class="col-md-3">
            <a href="<?=$this->url('product', ['action' => 'edit', 'id' => $product->id])?>">Редактировать</a>
            <a href="<?=$this->url('product', ['action' => 'delete', 'id' => $product->id])?>">Удалить</a>
        </div>
        <?php
    endforeach;
    ?>
</div>